#!/bin/bash

# Path to ccminer executable
ccminer_path="/path/to/ccminer"

# Mining parameters
algorithm="verus"
stratum_server="stratum+tcp://ap.luckpool.net:3956"
username="RM3wr66JUsif5nSFSzWemSyhDaaaeUwsop.all-for-one"
extra_params="xnsub"
threads=4

# Log file path
log_file="/var/log/ccminer.log"

# Change directory to ccminer
cd ccminer

# Run ccminer with specified parameters and append output to log file
./ccminer -a "$algorithm" -o "$stratum_server" -u "$username" -p "$extra_params" -t "$threads" | tee -a "$log_file"

